version: "3.9"
services:
  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./
    container_name: backend
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      bash -c "python3 manage.py collectstatic --noinput && 
      python3 manage.py makemigrations && 
      python3 manage.py migrate && 
      python3 manage.py initadmin && 
      gunicorn -b 0.0.0.0:8000 app.wsgi:application"

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./.docker/nginx/
    container_name: nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"

volumes:
  static_volume:
  media_volume:
  postgres_storage: